In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(
    "https://raw.githubusercontent.com/dylanmalis-collab/Exoplanet_Life/refs/heads/Machine_Learning/PSCompPars_2026.03.19_06.16.51.csv")
df.head()

,pl_name,hostname,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,sy_snum,sy_pnum,sy_mnum,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,11 Com b,11 Com,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,2,1,0,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,11 UMi b,11 UMi,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,1,1,0,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,14 And b,14 And,HD 221345,HIP 116076,TIC 333225860,Gaia DR2 1920113512486282240,Gaia DR3 1920113512486282240,1,1,0,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,14 Her b,14 Her,HD 145675,HIP 79248,TIC 219483057,Gaia DR2 1385293808145621504,Gaia DR3 1385293808145621504,1,2,0,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,16 Cyg B b,16 Cyg B,HD 186427,HIP 96901,TIC 27533327,Gaia DR2 2135550755683407232,Gaia DR3 2135550755683407232,3,1,0,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

In [2]:
df[df["pl_bmasse"] <= 5]

,pl_name,hostname,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,sy_snum,sy_pnum,sy_mnum,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
31,55 Cnc B b,55 Cnc B,NaN,NaN,TIC 332064684,Gaia DR2 704966762213039488,Gaia DR3 704966762213039488,2,7,0,...,-0.017100,13.15200,0.090,-0.090,7.666,0.023,-0.023,11.67980,0.000884,-0.000884
56,AU Mic d,AU Mic,HD 197481,HIP 102409,TIC 441420236,Gaia DR2 6794047652729201024,Gaia DR3 6794047652729201024,1,4,0,...,-0.004625,8.81000,0.100,-0.100,4.529,0.020,-0.020,7.84038,0.000731,-0.000731
90,Barnard b,Barnard's star,NaN,HIP 87937,TIC 325554331,Gaia DR2 4472832130942575872,Gaia DR3 4472832130942575872,1,4,0,...,-0.000975,9.54000,0.100,-0.100,4.524,0.020,-0.020,8.19511,0.001998,-0.001998
91,Barnard c,Barnard's star,NaN,HIP 87937,TIC 325554331,Gaia DR2 4472832130942575872,Gaia DR3 4472832130942575872,1,4,0,...,-0.000975,9.54000,0.100,-0.100,4.524,0.020,-0.020,8.19511,0.001998,-0.001998
92,Barnard d,Barnard's star,NaN,HIP 87937,TIC 325554331,Gaia DR2 4472832130942575872,Gaia DR3 4472832130942575872,1,4,0,...,-0.000975,9.54000,0.100,-0.100,4.524,0.020,-0.020,8.19511,0.001998,-0.001998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6135,rho CrB e,rho CrB,HD 143761,HIP 78459,TIC 458494003,Gaia DR2 1323427759184545536,Gaia DR3 1323427759184545536,1,4,0,...,-0.024000,5.40816,0.023,-0.023,3.857,0.036,-0.036,5.24167,0.002174,-0.002174
6137,tau Cet e,tau Cet,HD 10700,HIP 8102,TIC 419015728,Gaia DR2 2452378776434276992,Gaia DR3 2452378776434477184,1,4,0,...,-0.006750,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399
6138,tau Cet f,tau Cet,HD 10700,HIP 8102,TIC 419015728,Gaia DR2 2452378776434276992,Gaia DR3 2452378776434477184,1,4,0,...,-0.006750,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399
6139,tau Cet g,tau Cet,HD 10700,HIP 8102,TIC 419015728,Gaia DR2 2452378776434276992,Gaia DR3 2452378776434477184,1,4,0,...,-0.006750,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399
6140,tau Cet h,tau Cet,HD 10700,HIP 8102,TIC 419015728,Gaia DR2 2452378776434276992,Gaia DR3 2452378776434477184,1,4,0,...,-0.006750,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399

In [3]:
df.shape

(6147, 111)

In [4]:
df.describe()

,sy_snum,sy_pnum,sy_mnum,cb_flag,disc_year,pl_controv_flag,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
count,6147.000000,6147.000000,6147.0,6147.000000,6146.000000,6147.000000,5.814000e+03,5.322000e+03,5.322000e+03,5814.000000,...,6013.000000,5853.000000,5845.000000,5840.000000,5865.000000,5828.000000,5817.000000,5809.000000,5809.000000,5809.000000
mean,1.103628,1.774687,0.0,0.008622,2016.981939,0.007971,7.361952e+04,8.994706e+04,-2.054551e+04,-0.001032,...,-66.942415,12.545717,0.098134,-0.099630,10.377596,0.041517,-0.041532,12.253279,0.000644,-0.000644
std,0.342981,1.158518,0.0,0.092462,4.962135,0.088933,5.274625e+06,6.442906e+06,1.372810e+06,0.032111,...,278.681873,3.063023,0.135725,0.201793,2.994227,0.253471,0.259355,2.962278,0.001807,0.001807
min,1.000000,1.000000,0.0,0.000000,1992.000000,0.000000,9.070629e-02,0.000000e+00,-1.000000e+08,-1.000000,...,-2840.000000,0.872000,0.001000,-11.920000,-3.044000,0.011000,-9.995000,2.364310,0.000112,-0.063232
25%,1.000000,1.000000,0.0,0.000000,2014.000000,0.000000,4.350257e+00,1.200000e-05,-1.520000e-03,0.000000,...,-16.404000,10.610000,0.030000,-0.126000,8.353000,0.020000,-0.031000,10.356000,0.000257,-0.000543
50%,1.000000,1.000000,0.0,0.000000,2016.000000,0.000000,1.112900e+01,8.600000e-05,-8.700000e-05,0.000000,...,-3.999000,13.236000,0.070000,-0.069500,11.123000,0.023000,-0.023000,12.968200,0.000364,-0.000364
75%,1.000000,2.000000,0.0,0.000000,2021.000000,0.000000,3.978242e+01,1.540500e-03,-1.200000e-05,0.000000,...,-0.427000,14.943000,0.126000,-0.030000,12.732000,0.031000,-0.020000,14.679900,0.000543,-0.000257
max,4.000000,8.000000,0.0,1.000000,2026.000000,1.000000,4.020000e+08,4.700000e+08,0.000000e+00,0.000000,...,-0.000350,44.610000,3.100000,-0.001000,33.110000,9.995000,-0.011000,20.186100,0.063232,-0.000112

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6147 entries, 0 to 6146
Columns: 111 entries, pl_name to sy_gaiamagerr2
dtypes: float64(91), int64(6), str(14)
memory usage: 5.2 MB

In [21]:
pd.set_option('display.max_rows', None)
df.isna().sum()

pl_name                 0
hostname                0
hd_name              5104
hip_name             5011
tic_id                288
gaia_dr2_id           339
gaia_dr3_id           373
sy_snum                 0
sy_pnum                 0
sy_mnum                 0
cb_flag                 0
discoverymethod         0
disc_year               1
disc_facility           0
pl_controv_flag         0
pl_orbper             333
pl_orbpererr1         825
pl_orbpererr2         825
pl_orbperlim          333
pl_orbsmax            316
pl_orbsmaxerr1       2255
pl_orbsmaxerr2       2255
pl_orbsmaxlim         315
pl_rade                50
pl_radeerr1          1931
pl_radeerr2          1931
pl_radelim             50
pl_radj                50
pl_radjerr1          1931
pl_radjerr2          1931
pl_radjlim             50
pl_bmasse              31
pl_bmasseerr1        3166
pl_bmasseerr2        3166
pl_bmasselim           31
pl_bmassj              31
pl_bmassjerr1        3166
pl_bmassjerr2        3166
pl_bmassjlim           31
pl_bmassprov            0
pl_dens               138
pl_denserr1          4743
pl_denserr2          4743
pl_denslim            138
pl_orbeccen           936
pl_orbeccenerr1      4290
pl_orbeccenerr2      4290
pl_orbeccenlim        936
pl_insol             1839
pl_insolerr1         2519
pl_insolerr2         2519
pl_insollim          1839
pl_eqt               1562
pl_eqterr1           4344
pl_eqterr2           4344
pl_eqtlim            1562
pl_tranmid           1263
pl_tranmiderr1       1321
pl_tranmiderr2       1321
pl_tranmidlim        1263
ttv_flag                0
pl_occdep            6112
pl_occdeperr1        6115
pl_occdeperr2        6115
pl_occdeplim         6112
st_spectype          3849
st_teff               289
st_tefferr1           490
st_tefferr2           490
st_tefflim            289
st_rad                313
st_raderr1            472
st_raderr2            473
st_radlim             313
st_mass                 8
st_masserr1           278
st_masserr2           279
st_masslim              8
st_met                552
st_meterr1            836
st_meterr2            836
st_metlim             552
st_metratio           570
st_lum                307
st_lumerr1           2472
st_lumerr2           2478
st_lumlim             307
st_logg               317
st_loggerr1           496
st_loggerr2           496
st_logglim            317
st_dens               582
st_denserr1           712
st_denserr2           712
st_denslim            582
rastr                   0
ra                      0
decstr                  0
dec                     0
sy_dist                27
sy_disterr1           134
sy_disterr2           134
sy_vmag               294
sy_vmagerr1           302
sy_vmagerr2           307
sy_kmag               282
sy_kmagerr1           319
sy_kmagerr2           330
sy_gaiamag            338
sy_gaiamagerr1        338
sy_gaiamagerr2        338
Masse_(10^24kg)        31
Gravity_(G_earth)      74
Score_roch            139
pl_type                 0
sim_earth            1659
dtype: int64

In [6]:
df["Masse_(10^24kg)"] = df["pl_bmasse"].apply(lambda x: x * 5.972)
df["Masse_(10^24kg)"]

0       29351.773757
1       27977.710402
2        6755.235567
3       15285.167749
4        3378.583753
            ...
6142     1305.067132
6143    26535.036028
6144    19455.230278
6145      968.016336
6146     3684.156290
Name: Masse_(10^24kg), Length: 6147, dtype: float64

In [7]:
df["Gravity_(G_earth)"] = df["pl_bmasse"] * df["pl_rade"]
df["Gravity_(G_earth)"]

0       59961.761527
1       57623.214660
2       14818.082037
3       32249.349236
4        7637.454900
            ...
6142     3059.434000
6143    54651.865897
6144    40721.764647
6145     2301.713323
6146     8266.526169
Name: Gravity_(G_earth), Length: 6147, dtype: float64

In [8]:
df["Score_roch"] = df["pl_dens"] * (1/df["pl_rade"])**3
df["Score_roch"]

0       0.008206
1       0.007416
2       0.001228
3       0.003514
4       0.000512
          ...
6142    0.000160
6143    0.007040
6144    0.004695
6145    0.000109
6146    0.000586
Name: Score_roch, Length: 6147, dtype: float64

In [9]:
df["pl_type"] = df["Score_roch"].apply(lambda x: "Rocheuse" if x > 3.5 else "Gazeuse/Mixte")
df["pl_type"].value_counts()

pl_type
Gazeuse/Mixte    5646
Rocheuse          501
Name: count, dtype: int64

In [10]:
df["sim_earth"] = (
    (1 - np.abs((df["pl_rade"] - 1) / (df["pl_rade"] + 1))) ** 0.57 *
    (1 - np.abs((df["pl_dens"] - 5.51) / (df["pl_dens"] + 5.51))) ** 1.07 *
    (1 - np.abs((df["Gravity_(G_earth)"] - 1) / (df["Gravity_(G_earth)"] + 1))) ** 0.70 *
    (1 - np.abs((df["pl_eqt"] - 288) / (df["pl_eqt"] + 288))) ** 5.58
) ** 0.25

C:\Users\berna\AppData\Local\Temp\ipykernel_28108\3058808861.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["sim_earth"] = (

In [14]:
df["sim_earth"].isna().sum()

np.int64(1659)

In [15]:
df["pl_rade"].isna().sum()

np.int64(50)

In [16]:
df["pl_dens"].isna().sum()

np.int64(138)

In [17]:
df["Gravity_(G_earth)"].isna().sum()

np.int64(74)

In [18]:
df["pl_eqt"].isna().sum()

np.int64(1562)